sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

before_install:
  - nvm install 6
  - nvm use 6

install:
  - npm install

before_script:
  - nvm use $TRAVIS_NODE_VERSION
